# Generated by Django 2.1.2 on 2018-10-19 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DetailRegistration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('birth_year', models.IntegerField()),
                ('address', models.CharField(max_length=100)),
                ('tip', models.IntegerField()),
                ('message', models.TextField()),
                ('fri_breakfast', models.BooleanField()),
                ('fri_lunch', models.BooleanField()),
                ('fri_dinner', models.BooleanField()),
                ('sat_breakfast', models.BooleanField()),
                ('sat_lunch', models.BooleanField()),
                ('sat_dinner', models.BooleanField()),
                ('sun_breakfast', models.BooleanField()),
                ('sun_lunch', models.BooleanField()),
                ('fri_night', models.CharField(choices=[('Postel', 'Ubytování s příslušenstvím - postel'), ('Spacak', 'Ubytování spacák a karimatka'), ('Sirak', 'Bez ubytovani')], max_length=10)),
                ('sat_night', models.CharField(choices=[('Postel', 'Ubytování s příslušenstvím - postel'), ('Spacak', 'Ubytování spacák a karimatka'), ('Sirak', 'Bez ubytovani')], max_length=10)),
                ('reg_id', models.IntegerField()),
                ('status', models.CharField(choices=[('Ceka na zaplaceni', 'Ceka na zaplaceni'), ('Zaplaceno', 'Zaplaceno'), ('Platba vyprsela', 'Platba vyprsela'), ('Zruseno', 'Zruseno')], max_length=10)),
                ('internal_message', models.TextField()),
                ('price', models.IntegerField()),
                ('date_created', models.DateField()),
                ('var_symbol', models.IntegerField()),
                ('reg_type', models.CharField(choices=[('Ucastnik', 'Ucastnik'), ('Dobrovolnik', 'Dobrovolnik'), ('Host', 'Host'), ('Duchovni', 'Duchovni'), ('Tym', 'Tym')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='SimpleRegistration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('birth_year', models.IntegerField()),
                ('address', models.CharField(max_length=100)),
                ('accommodation', models.CharField(choices=[('Postel', 'Ubytování s příslušenstvím - postel'), ('Spacak', 'Ubytování spacák a karimatka'), ('Sirak', 'Bez ubytovani')], max_length=10)),
                ('tip', models.IntegerField()),
                ('message', models.TextField()),
            ],
        ),
    ]
